In [1]:
import pandas as pd

In [2]:
# sales = pd.read_excel("sales_customer.xlsx")
sales = pd.read_excel("sales_customer_small.xlsx")

In [3]:
# Display the first few rows of the DataFrame
sales.head()

,Date,Customer ID,Country,State,Product Category,Sub Category,Product,Order Quantity,Unit Cost,Unit Price,...,Profit,Margin,MaritalStatus,YearlyIncome,TotalChildren,EnglishEducation,HouseOwnerFlag,Age,Gender,Age Group
0,2016-06-18,28257,United States,Washington,Bikes,Road Bikes,"Road-150 Red, 44",1,2171,3578,...,1407,0.393236,S,100000,1,Partial College,True,34,Male,Adult
1,2011-04-20,11901,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",2,1266,2320,...,2108,0.454310,S,60000,2,Bachelors,False,31,Male,Adult
2,2012-07-05,23909,France,Seine (Paris),Bikes,Road Bikes,"Road-750 Black, 58",2,344,540,...,392,0.362963,M,30000,1,Bachelors,True,35,Female,Adult
3,2015-10-24,13015,United States,Oregon,Accessories,Tires and Tubes,Mountain Tire Tube,8,2,5,...,24,0.600000,S,100000,2,Bachelors,False,33,Male,Adult
4,2016-04-21,22348,United States,California,Accessories,Bottles and Cages,Water Bottle - 30 oz.,18,2,5,...,54,0.600000,M,30000,2,High School,True,48,Male,Adult

In [4]:
# Get the shape of the DataFrame
sales.shape

(11203, 22)

In [5]:
# Get the column names of the DataFrame
sales.columns

Index(['Date', 'Customer ID', 'Country', 'State', 'Product Category',
       'Sub Category', 'Product', 'Order Quantity', 'Unit Cost', 'Unit Price',
       'Total Cost', 'Total Revenue', 'Profit', 'Margin', 'MaritalStatus',
       'YearlyIncome', 'TotalChildren', 'EnglishEducation', 'HouseOwnerFlag',
       'Age', 'Gender', 'Age Group'],
      dtype='object')

In [6]:
# Get summary statistics of the DataFrame
sales.describe()

,Date,Customer ID,Order Quantity,Unit Cost,Unit Price,Total Cost,Total Revenue,Profit,Margin,YearlyIncome,TotalChildren,Age
count,11203,11203.000000,11203.000000,11203.000000,11203.000000,11203.000000,11203.000000,11203.000000,11203.000000,11203.000000,11203.000000,11203.000000
mean,2014-11-22 22:11:07.749709824,19249.502276,11.951709,264.897260,448.885299,470.161475,842.063733,371.902258,0.526135,59646.523253,1.828707,34.656253
min,2011-01-01 00:00:00,11005.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,0.222222,10000.000000,0.000000,18.000000
25%,2013-12-21 00:00:00,14586.000000,2.000000,2.000000,5.000000,27.000000,70.000000,39.000000,0.437647,30000.000000,0.000000,28.000000
50%,2014-06-28 00:00:00,18637.000000,10.000000,9.000000,24.000000,112.000000,245.000000,135.000000,0.600000,60000.000000,2.000000,34.000000
75%,2016-01-12 00:00:00,23512.000000,20.000000,42.000000,70.000000,456.000000,880.000000,432.000000,0.628571,80000.000000,3.000000,41.000000
max,2016-07-31 00:00:00,29483.000000,32.000000,2171.000000,3578.000000,8684.000000,14312.000000,5952.000000,0.750000,170000.000000,5.000000,68.000000
std,NaN,5312.052181,9.526736,545.076699,914.350085,871.740421,1445.866747,588.196480,0.139120,33684.368671,1.598693,9.529838

In [7]:
# Count occurrences of each product category
sales["Product Category"].value_counts()

Product Category
Accessories    6918
Bikes          2580
Clothing       1705
Name: count, dtype: int64

In [8]:
# Inspect the number of records for each combination of Product Category, Sub Category, and Product
sp = sales.groupby(["Product Category", "Sub Category", "Product"]).size().reset_index().rename(columns={0: "Count"})
sp.sort_values(by="Count", ascending=False)

    Product Category       Sub Category                  Product  Count
19       Accessories    Tires and Tubes      Patch Kit/8 Patches   1066
5        Accessories  Bottles and Cages    Water Bottle - 30 oz.   1062
18       Accessories    Tires and Tubes       Mountain Tire Tube    673
111         Clothing               Caps             AWC Logo Cap    448
20       Accessories    Tires and Tubes           Road Tire Tube    431
..               ...                ...                      ...    ...
50             Bikes     Mountain Bikes  Mountain-500 Silver, 52      3
23             Bikes     Mountain Bikes   Mountain-100 Black, 38      3
26             Bikes     Mountain Bikes   Mountain-100 Black, 48      3
24             Bikes     Mountain Bikes   Mountain-100 Black, 42      3
2        Accessories        Bike Stands      Hitch Rack - 4-Bike      1

[131 rows x 4 columns]

In [9]:
# Pivot table to see counts of products in each sub-category within product categories
sales.pivot_table(index=["Product Category"], columns=["Sub Category"], aggfunc="size").fillna(0)

Sub Category,Bike Racks,Bike Stands,Bottles and Cages,Caps,Cleaners,Fenders,Gloves,Helmets,Hydration Packs,Jerseys,Mountain Bikes,Road Bikes,Shorts,Socks,Tires and Tubes,Touring Bikes,Vests
Product Category,,,,,,,,,,,,,,,,,
Accessories,66.0,47.0,1539.0,0.0,196.0,395.0,0.0,1197.0,123.0,0.0,0.0,0.0,0.0,0.0,3355.0,0.0,0.0
Bikes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,873.0,1310.0,0.0,0.0,0.0,397.0,0.0
Clothing,0.0,0.0,0.0,448.0,0.0,0.0,281.0,0.0,0.0,610.0,0.0,0.0,163.0,114.0,0.0,0.0,89.0

In [10]:
# Calculate total profit by Product Category and Sub Category
sales.groupby(["Product Category", "Sub Category"])['Profit'].sum().reset_index().sort_values(by="Profit", ascending=False)

   Product Category       Sub Category   Profit
9             Bikes         Road Bikes  1389881
8             Bikes     Mountain Bikes  1068022
5       Accessories            Helmets   404096
10            Bikes      Touring Bikes   317739
7       Accessories    Tires and Tubes   307454
13         Clothing            Jerseys   108576
14         Clothing             Shorts   106392
2       Accessories  Bottles and Cages    91053
4       Accessories            Fenders    87556
6       Accessories    Hydration Packs    62798
12         Clothing             Gloves    61095
16         Clothing              Vests    51040
0       Accessories         Bike Racks    44025
1       Accessories        Bike Stands    27325
3       Accessories           Cleaners    14515
11         Clothing               Caps    14030
15         Clothing              Socks    10824